# Generated by Django 3.1.4 on 2020-12-20 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('slug', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
